hw12 is done
romandnk/HW pull request #13
Opened 2023-07-13 21:42 UTC by romandnk

2023-07-14 17:16 UTC, dshemin requested changes

2023-07-14 17:16 UTC, dshemin commented on hw12_13_14_15_calendar/cmd/calendar/config.go
> +func NewLoggerConf() LoggerConf {
Важно:

Нам точно нужно давать доступ к этой функции извне пакета?

2023-07-14 17:16 UTC, dshemin commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +	// if flag.Arg(0) == "version" {
Важно:

Надо будет вернуть.

2023-07-14 17:16 UTC, dshemin commented on hw12_13_14_15_calendar/configs/config.toml
> +sssmode = "disable"
Важно:

`sslmode`

2023-07-14 17:16 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +		Addr:           cfg.Host + ":" + cfg.Port,
Важно:

Для правильной конкатенации хоста и порта есть функция в стандартных пакетах голанг.

2023-07-14 17:50 UTC, romandnk commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +		Addr:           cfg.Host + ":" + cfg.Port,
Постоянно забываю о ней...)

2023-07-17 00:28 UTC, dshemin requested changes

2023-07-17 00:28 UTC, dshemin commented on hw12_13_14_15_calendar/cmd/calendar/config.go
> +	Memory bool
Совет:

Для ДЗ пойдёт, но в реальном проекте лучше использовать строковое поле чтобы иметь возможность добавлять новые типы стораджей не ломая конфиг.

2023-07-17 00:28 UTC, dshemin commented on hw12_13_14_15_calendar/cmd/calendar/config.go
> +	return &config
Важно:

Нет валидации конфига. Я могу что угодно напередавать и это сломает приложение где-то потом. А лучше тут отсечь все неверные варианты.

2023-07-17 00:28 UTC, dshemin commented on hw12_13_14_15_calendar/cmd/calendar/config.go
> +		log.Fatalf("fatal error config file: %s\n", err)
Важно:

Не надо делать log.Fatal() в утилитарных функциях. Это остановит всё приложение. Верните ошибку.

2023-07-17 00:28 UTC, dshemin commented on hw12_13_14_15_calendar/internal/logger/logger.go
> +			log = slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelInfo}))
Важно:

Крайне неудобно читать - куча копипасты. Сначала выбирете уровень логирования, потом тип хендлера. И код станет легче поддерживать.

2023-07-17 00:28 UTC, dshemin commented on hw12_13_14_15_calendar/internal/logger/logger.go
> +	return log
Важно:

Потенциально тут может вернутся nil если кто-то ошибётся с representation. В итоге получим где-то в коде попытку разыменования nil указателя и панику.

Верните ошибку если representation не один из ожидаемых параметров.

2023-07-17 00:28 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/middleware.go
> +		log.Info("Request info",
Критично:

Не всё собирается и выводится:

> IP клиента;
> дата и время запроса;
> метод, path и версия HTTP;
> код ответа;
> latency (время обработки запроса, посчитанное, например, с помощью middleware);
> user agent, если есть.

Сейчас есть только метод, путь и латенси.

2023-07-17 00:28 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/event.go
> +	query := fmt.Sprintf(`DELETE FROM %s WHERE id = $1 RETURNING id`, eventsTable)
Важно:

Мы просим удалить запись по id, зачем нам возвращать её id, если он нам уже известен?

2023-07-17 00:28 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +//go:generate mockgen -source=storage.go -destination=.mock/mock.go sqlstorage
Важно:

Секции  `//go:` должны идти в начале файла, после декларации названия пакета и до импортов. Так как у Вас - работает, но писать не принято.

2023-07-20 00:33 UTC, dshemin requested changes

2023-07-20 00:33 UTC, dshemin commented on hw12_13_14_15_calendar/internal/logger/logger.go
> +	return log
Всё ещё валидно.

2023-07-20 00:33 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/memory/event.go
> +		return []models.Event{}, ctx.Err()
Важно:

Тут у нас произойдёт выделение памяти которое можно избежать, вернув просто nil вместо []models.Event{}

2023-07-20 00:33 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/memory/event.go
> +		return []models.Event{}, ctx.Err()
Важно:

Тут у нас произойдёт выделение памяти которое можно избежать, вернув просто nil вместо []models.Event{}

2023-07-20 00:33 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/memory/event.go
> +		return []models.Event{}, ctx.Err()
Важно:

Тут у нас произойдёт выделение памяти которое можно избежать, вернув просто nil вместо []models.Event{}

2023-07-20 00:33 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/memory/event_test.go
> +		id, _ := st.Create(ctx, event)
Важно:

Игнорирование ошибки. В тестах так же надо проверять на ошибку иначе потом можно долго отлаживать падение где-то в другом месте.

2023-07-20 00:33 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/memory/event_test.go
> +	if len(st.events) != 100 {
Важно:

https://pkg.go.dev/github.com/stretchr/testify/require#Len

2023-07-20 00:33 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/memory/event_test.go
> +			require.True(t, reflect.DeepEqual(actualDates, tc.expected))
Важно:

Посмотрите внимательно как работает require.Equal.

https://github.com/stretchr/testify/blob/v1.8.4/require/require.go#L162
https://github.com/stretchr/testify/blob/master/assert/assertions.go#L414
https://github.com/stretchr/testify/blob/master/assert/assertions.go#L65

2023-07-20 00:33 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/memory/event_test.go
> +			sort.Slice(actualDates, func(i, j int) bool {
Важно:

https://pkg.go.dev/github.com/stretchr/testify/require#ElementsMatch

2023-07-20 00:33 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/event_test.go
> +	if err != nil {
Важно:

https://pkg.go.dev/github.com/stretchr/testify/require#NoError

2023-07-20 00:33 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/event_test.go
> +	if err = mock.ExpectationsWereMet(); err != nil {
Важно:

https://pkg.go.dev/github.com/stretchr/testify/require#NoErrorf

2023-07-20 00:33 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/event_test.go
> +	if err != nil {
Важно:

https://pkg.go.dev/github.com/stretchr/testify/require#NoError

Давольно много мест где вы не используете по полной все доступные ассёрты. Пожалуйста посмотрите внимательно на либу, там много полезных функций.

2023-07-21 05:53 UTC, dshemin approved these changes

2023-07-21 05:53 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/memory/event_test.go
> +		require.Equal(t, fmt.Errorf("updating: no event with id %s", event.ID), err)
Важно:

https://pkg.go.dev/github.com/stretchr/testify/require#EqualError

2023-07-21 05:53 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/memory/event_test.go
> +		require.Equal(t, fmt.Errorf("deleting: no event with id %s", id), err)
Важно:

https://pkg.go.dev/github.com/stretchr/testify/require#EqualError

2023-07-22 05:10 UTC, dshemin approved these changes

2023-07-22 16:07 UTC, merged