hw14 is done
romandnk/HW pull request #15
Opened 2023-08-12 14:57 UTC by romandnk

2023-08-15 18:04 UTC, dshemin requested changes

2023-08-15 18:04 UTC, dshemin commented on hw12_13_14_15_calendar/internal/mq/mq.go
> +type Scheduler interface {
Важно:

В случаи брокеров сообщений у нас есть publisher и consumer. Scheduler и Sender - это уже наша бизнес логика.

2023-08-15 18:04 UTC, dshemin commented on hw12_13_14_15_calendar/internal/mq/rabbitmq/sender.go
> +func (s *Sender) Handle(ctx context.Context) <-chan Notification {
Важно:

Эту логику нам придётся копировать во все реализации интерфейса. Более того этого метода нет в интерфейсе, он точно должен быть публичным?

2023-08-15 18:04 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/postgres/storage.go
> +	p.db.Close()
Важно:

Игнорируем ошибку.

2023-08-15 19:34 UTC, romandnk commented on hw12_13_14_15_calendar/internal/storage/postgres/storage.go
> +	p.db.Close()
там метод не возвращает ошибки

2023-08-18 18:56 UTC, dshemin approved these changes

2023-08-18 18:56 UTC, dshemin commented on hw12_13_14_15_calendar/internal/mq/rabbitmq/consumer.go
> +	done <- struct{}{}
Важно:

Тут можно просто сразу закрыть канал notifications.  И упростить код.

2023-08-18 18:56 UTC, dshemin commented on hw12_13_14_15_calendar/internal/mq/mq.go
> +	Consume() error
Важно:

В итоге консюмер будет содержать и технический код (соединене с кроликом, открытие каналов и т.п.) и бизнес код (на данный момент логирование). Уже нарушаем принцип единой ответственности.

Теперь давайте представим что у нас потом появится поддержка NATS, Kafka и т.п. и бизнес логика поменяется. С текущим интерфейсом нам придётся копировать бизнес логику во все имплементации. Надо сделать так:

```
type Consumer interface {
    Consume() (<-chan Notification, error)
}
```

2023-08-18 18:56 UTC, dshemin commented on hw12_13_14_15_calendar/internal/mq/rabbitmq/consumer.go
> +	done    chan struct{}
Важно:

Данный канал используется только в одной функции. Он не должен быть частью типа.

2023-08-19 19:30 UTC, dshemin approved these changes

2023-08-19 20:48 UTC, merged